package dmacc.beans;
//Manuel Corral Ledezma
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Inventory {
	//TODO make autogenerated, @GeneratedValue isn't lombok / working
	private long id;
	private String itemName;
	private String itemLocation;
	private String itemDescription;
	
	public Inventory(long itemId, String itemName) {
		super();
		this.id = itemId;
		this.itemName = itemName;
	}
	
	public Inventory(long itemId, String itemName, String itemLocation, String itemDescription) {
		super();
		this.id = itemId;
		this.itemName = itemName;
		this.itemLocation = itemLocation;
		this.itemDescription = itemDescription;
	}
}
