package dmacc.beans;
import lombok.AllArgsConstructor;
//Manuel Corral Ledezma
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Inventory {
	//TODO make autogenerated, @GeneratedValue isn't lombok / working
	private long id;
	private String itemName;
	private String itemLocation;
	private String itemDescription;
	
	public Inventory(long itemId, String itemName) {
		super();
		this.id = itemId;
		this.itemName = itemName;
	}

}
